/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Ctrl_Usuarios;
import Modelo.Consulta_Usuarios;
import Modelo.Usuarios;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;

/**
 *
 * @author monta
 */
public class frmLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
        char echoChar= '*';
        this.txtclave.setEchoChar(echoChar);
        this.txtclave.setForeground(Color.BLACK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        btningresar = new javax.swing.JButton();
        btnolvidado = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtclave = new javax.swing.JPasswordField();
        btnver = new javax.swing.JButton();
        btnocultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 32, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Ingrese Usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 95, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Ingrese Contraseña");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 208, -1, -1));

        txtnombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 92, 182, -1));

        btningresar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btningresar.setText("Ingresar");
        btningresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresarActionPerformed(evt);
            }
        });
        getContentPane().add(btningresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        btnolvidado.setText("Has olvidado Tu Contraseña");
        btnolvidado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnolvidadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnolvidado, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, -1, -1));

        jButton1.setText("Registrate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 335, -1, -1));

        txtclave.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtclave, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 205, 182, 40));

        btnver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_eye_24px.png"))); // NOI18N
        btnver.setBorder(null);
        btnver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverActionPerformed(evt);
            }
        });
        getContentPane().add(btnver, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 38, 31));

        btnocultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_eyelashes_2d_24px.png"))); // NOI18N
        btnocultar.setBorder(null);
        btnocultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnocultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnocultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 38, 31));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btningresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresarActionPerformed
        if("".equals(txtnombre.getText())){
            JOptionPane.showMessageDialog(null, "Ingrese datos en el campo usuario");
        }
        else if("".equals(txtclave.getText())){
            JOptionPane.showMessageDialog(null, "Ingrese datos en el campo Clave");
        }else{
            Usuarios usuarios = new Usuarios();
            Consulta_Usuarios consulta_Usuarios = new Consulta_Usuarios();
            String user,clave;
            user=this.txtnombre.getText();
            clave=this.txtclave.getText();
            Ctrl_Usuarios ctrl=new Ctrl_Usuarios(usuarios, consulta_Usuarios);
            if(ctrl.Login(user, clave)){
                this.txtnombre.setText("");
                this.txtclave.setText("");
            }
            else{
                this.txtnombre.setText("");
                this.txtclave.setText("");
            }
        }
        

    }//GEN-LAST:event_btningresarActionPerformed

    private void btnolvidadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnolvidadoActionPerformed
       frmRecuperacion recuperacion = new frmRecuperacion();
       recuperacion.setVisible(true);
       dispose();
    }//GEN-LAST:event_btnolvidadoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        frmUsuario usuario = new frmUsuario();
       usuario.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverActionPerformed
        txtclave.setEchoChar((char) 0);
        btnver.setVisible(false);
        btnocultar.setVisible(true);
    }//GEN-LAST:event_btnverActionPerformed

    private void btnocultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnocultarActionPerformed
        char echoChar= '*';
        SimpleAttributeSet attributeSet = new SimpleAttributeSet();
        StyleConstants.setBold(attributeSet, true);
        this.txtclave.setEchoChar(echoChar);
        this.txtclave.setForeground(Color.BLACK);
         btnver.setVisible(true);
        btnocultar.setVisible(false);
    }//GEN-LAST:event_btnocultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btningresar;
    private javax.swing.JButton btnocultar;
    private javax.swing.JButton btnolvidado;
    private javax.swing.JButton btnver;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtclave;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
